Support Config.node false value
neutrinojs/webpack-chain pull request #252
Opened 2020-03-30 15:14 UTC by SuperOleg39

Resolves #209.

2020-06-08 00:21 UTC, opl- requested changes
One problem I have with this approach is that doing `config.set('node', {})` will force the node property to never show up in the final config, which might end up being extremely confusing to a user who might not expect `config.delete('node')` to be the way to bring back the standard behavior. Similarly, using `config.set('node', [])` will cause even more weirdness to happen.

I see three potential solutions to this problem:
- Ignore this and call it a feature,
- Ignore any value other than `false`,
- Override the `config.set` function and raise an error.

I'm not sure what the standard is in this library, so I'm just mentioning it and leaving any decisions up to the maintainers. If the first option is chosen, I'd recommend at least changing the documentation accordingly.

2020-06-08 00:21 UTC, opl- commented on README.md
> +`false` value always rewrite `config.node` object.
```suggestion
You can set the `node` option to an object, or a `false` value.
A `false` value always overrides the `config.node` chained map.
```

2020-06-08 00:21 UTC, opl- commented on README.md
> +config.set('node', false);
```suggestion
config.set('node', false);

// To use the value generated from `config.node` ChainedMap again
config.delete('node');
```

2020-06-08 00:21 UTC, opl- commented on src/Config.js
> +      if (typeof obj.node === 'object') {
`true` for `obj.node == []`. Though the input is unexpected it might cause issues.

2020-06-08 01:02 UTC, opl- commented
I'd also like to mention the possibility of creating [callable classes](https://stackoverflow.com/questions/36871299/how-to-extend-function-with-es6-classes) even though I feel it's rather hacky. Something like this could also be used for #222 (though that one could be resolved without weird hacks by introducing a breaking change and bumping the major).

2020-07-01 21:06 UTC, edmorley commented
@SuperOleg39 thank you for the PR and @opl- thank you for the really helpful review/thoughts. I don't use webpack day to day any more, so am reliant on suggestions as to what direction it should take longer term. I agree with @opl- 's thoughts about potentially confusing UX. What do you both think as the best option out of those that are proposed above?

2024-02-03 19:30 UTC, edmorley commented
Closing since this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358

2024-02-03 19:30 UTC, closed without merging